name: islami_r
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:

  flutter:
    sdk: flutter

  dio:
  dartz:
  provider: ^6.1.2
  animated_custom_dropdown: 3.1.1
  audioplayers:
  shared_preferences: ^2.3.2




  flutter_localizations:
    sdk: flutter
  intl: any





  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/files/




  fonts:
     - family: El Messiri
       fonts:
         - asset: assets/fonts/ElMessiri-Bold.ttf
         - asset: assets/fonts/ElMessiri-SemiBold.ttf
         - asset: assets/fonts/ElMessiri-Medium.ttf
         - asset: assets/fonts/ElMessiri-Bold.ttf
